version: "3.8"

services:
  db:
    image: mongo:latest
    container_name: mongo_cine
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  admin:
    image: mongo-express:latest
    container_name: mongo_express_cine
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    depends_on:
      - db
    restart: always

  web:
    build: .
    container_name: target_cine_flask
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/cine
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    restart: always

volumes:
  mongo_data:
